UPDATE public.application SET date = '2018-11-22 06:53:47.022525', loading_address = 'Kazan', unloading_address = 'Moskow', weight = 10000, payment = 30000, customer_id = 7, carrier_id = null, loading_type = 'with sides' WHERE id = 10;
UPDATE public.application SET date = '2018-11-22 06:55:49.998541', loading_address = 'Kazan', unloading_address = 'Chebocksary', weight = 15000, payment = 60000, customer_id = 7, carrier_id = null, loading_type = 'without gates' WHERE id = 11;
UPDATE public.application SET date = '2018-11-22 09:37:50.098530', loading_address = 'Kazan', unloading_address = 'Ekb', weight = 1000, payment = 10000, customer_id = 7, carrier_id = null, loading_type = 'tail lift' WHERE id = 13;
UPDATE public.application SET date = '2018-11-22 11:31:16.816589', loading_address = 'ugf', unloading_address = 'jkgh', weight = 7, payment = 7, customer_id = 8, carrier_id = null, loading_type = 'top' WHERE id = 14;
UPDATE public.application SET date = '2018-11-18 19:14:54.952000', loading_address = 'Kazan,Fuchika 88', unloading_address = 'Chelny , Prospect Mira 10', weight = 10000, payment = 15000, customer_id = 6, carrier_id = null, loading_type = 'top' WHERE id = 6;
UPDATE public.application SET date = '2018-11-18 13:14:54.952000', loading_address = 'Ekaterinburg', unloading_address = 'Moskow', weight = 20000, payment = 100000, customer_id = 6, carrier_id = null, loading_type = 'top' WHERE id = 8;
UPDATE public.application SET date = '2018-11-18 19:14:54.952000', loading_address = 'Kazan', unloading_address = 'Moskow', weight = 15000, payment = 20000, customer_id = 6, carrier_id = null, loading_type = 'back' WHERE id = 7;
UPDATE public.application SET date = '2018-11-22 08:30:18.072959', loading_address = 'Akibastus', unloading_address = 'Ulan-ude', weight = 10000, payment = 150000, customer_id = 7, carrier_id = null, loading_type = 'top' WHERE id = 12;
UPDATE public.application SET date = '2018-12-10 10:45:57.678431', loading_address = 'Kazan', unloading_address = 'Moskow', weight = 20000, payment = 15000, customer_id = 9, carrier_id = null, loading_type = 'side' WHERE id = 15;
UPDATE public.application SET date = '2018-12-10 11:00:42.436986', loading_address = 'Kazan', unloading_address = 'Chebocksary', weight = 10000, payment = 20000, customer_id = 9, carrier_id = null, loading_type = 'back' WHERE id = 16;
UPDATE public.application SET date = '2018-12-24 10:43:45.203495', loading_address = 'Kazan', unloading_address = 'Moskow', weight = 15, payment = 15500, customer_id = 7, carrier_id = null, loading_type = 'without gates' WHERE id = 17;
UPDATE public.application SET date = '2018-12-24 10:59:25.189950', loading_address = 'Kazan', unloading_address = 'Chebocksary', weight = 15000, payment = 15500, customer_id = 7, carrier_id = null, loading_type = 'tail lift' WHERE id = 18;
UPDATE public.application SET date = '2018-12-24 10:59:57.622407', loading_address = 'Kazan', unloading_address = 'Ekaterinburg', weight = 10000, payment = 20000, customer_id = 7, carrier_id = null, loading_type = 'with full removable curtains' WHERE id = 19;
UPDATE public.application SET date = '2018-12-24 11:30:04.534340', loading_address = 'Kazan', unloading_address = 'Ekaterinburd', weight = 10000, payment = 12000, customer_id = 9, carrier_id = null, loading_type = 'side' WHERE id = 20;
UPDATE public.application SET date = '2018-12-24 11:30:14.268757', loading_address = 'Kazan', unloading_address = 'Ekaterinburd', weight = 10000, payment = 12000, customer_id = 9, carrier_id = null, loading_type = 'side' WHERE id = 21;
UPDATE public.application SET date = '2018-12-24 11:30:15.095559', loading_address = 'Kazan', unloading_address = 'Ekaterinburd', weight = 10000, payment = 12000, customer_id = 9, carrier_id = null, loading_type = 'side' WHERE id = 22;
UPDATE public.application SET date = '2018-12-24 11:30:15.235959', loading_address = 'Kazan', unloading_address = 'Ekaterinburd', weight = 10000, payment = 12000, customer_id = 9, carrier_id = null, loading_type = 'side' WHERE id = 23;
UPDATE public.application SET date = '2018-12-24 11:30:57.356033', loading_address = 'Kazan', unloading_address = 'Ekaterinburd', weight = 10000, payment = 12000, customer_id = 9, carrier_id = null, loading_type = 'side' WHERE id = 24;
UPDATE public.auth_cookie SET cookie_value = 'df792360-d1e8-4dbb-9dec-c8e6dba4770e', user_id = 1 WHERE id = 1;
UPDATE public.auth_cookie SET cookie_value = '0709fc5b-60cf-43cb-94f1-6b51fe98397b', user_id = 1 WHERE id = 2;
UPDATE public.auth_cookie SET cookie_value = '1038f84e-a37f-4c15-8a47-0278aeec088c', user_id = 3 WHERE id = 3;
UPDATE public.auth_cookie SET cookie_value = '0fa20aec-1836-4298-ae4b-ccdd72a752f5', user_id = 1 WHERE id = 4;
UPDATE public.auth_cookie SET cookie_value = '3fb8b90f-2884-4c61-97c4-e249fa3bc61b', user_id = 16 WHERE id = 5;
UPDATE public.auth_cookie SET cookie_value = '38865042-a6b4-40be-a86f-2520fec89dc3', user_id = 16 WHERE id = 6;
UPDATE public.auth_cookie SET cookie_value = '9874dac0-b8c8-4c36-98f5-616985cf130b', user_id = 16 WHERE id = 7;
UPDATE public.auth_cookie SET cookie_value = 'e8435c07-a8d2-4b71-b583-1494000d7c95', user_id = 16 WHERE id = 8;
UPDATE public.auth_cookie SET cookie_value = '4d5bb736-fac0-4059-9428-edde0d1914ce', user_id = 16 WHERE id = 9;
UPDATE public.auth_cookie SET cookie_value = '576fdf79-93d8-4979-a1e1-669a5da52046', user_id = 16 WHERE id = 10;
UPDATE public.auth_cookie SET cookie_value = '0d7c4382-719b-453c-9192-4930f3878d4d', user_id = 16 WHERE id = 11;
UPDATE public.auth_cookie SET cookie_value = 'e3b8ef98-9a33-47b0-bb44-4a919974773f', user_id = 16 WHERE id = 12;
UPDATE public.auth_cookie SET cookie_value = 'daab3469-8a69-4f5d-980d-d38c02d5bc26', user_id = 17 WHERE id = 13;
UPDATE public.auth_cookie SET cookie_value = '0bb5f921-a49a-409d-b65c-385c61b5ff8d', user_id = 16 WHERE id = 14;
UPDATE public.auth_cookie SET cookie_value = 'caf22cd9-6266-479d-8350-f5916d29fdd0', user_id = 17 WHERE id = 15;
UPDATE public.auth_cookie SET cookie_value = 'ab2feacb-193f-4230-962a-d1aaca0b5bbc', user_id = 16 WHERE id = 16;
UPDATE public.auth_cookie SET cookie_value = '184a139e-da8e-445f-9489-22c37e340fbc', user_id = 1 WHERE id = 17;
UPDATE public.auth_cookie SET cookie_value = 'a5a74ffe-14df-48cc-9ce8-8b06786c4dd6', user_id = 16 WHERE id = 18;
UPDATE public.auth_cookie SET cookie_value = 'e123464d-1771-4b0a-a223-337e14143ed6', user_id = 16 WHERE id = 19;
UPDATE public.auth_cookie SET cookie_value = 'e13d716f-7397-4d9c-a11d-99f25b7a0cc2', user_id = 16 WHERE id = 20;
UPDATE public.auth_cookie SET cookie_value = 'e6c244e0-2bcb-434f-9cee-8e5a4d1b8e2c', user_id = 16 WHERE id = 21;
UPDATE public.auth_cookie SET cookie_value = 'b57e2772-a65c-4acd-afd1-e999a887b6d8', user_id = 16 WHERE id = 22;
UPDATE public.auth_cookie SET cookie_value = 'c9dd244d-523a-486c-946c-49e23b9dc1ea', user_id = 2 WHERE id = 23;
UPDATE public.auth_cookie SET cookie_value = '28b34d17-a26e-4f9f-a3f6-2a508925d93c', user_id = 18 WHERE id = 24;
UPDATE public.auth_cookie SET cookie_value = '6ee8c1f6-07b9-471e-9c87-0038c3f0daac', user_id = 1 WHERE id = 25;
UPDATE public.auth_cookie SET cookie_value = 'c130e014-2f32-4545-8dd7-e173b7b09105', user_id = 1 WHERE id = 26;
UPDATE public.auth_cookie SET cookie_value = '9e2ddb1f-05d3-4158-8f54-6bd57fbe5de8', user_id = 19 WHERE id = 27;
UPDATE public.auth_cookie SET cookie_value = 'b5f0c1ca-2677-4fc9-b18b-9c4fb018fd50', user_id = 1 WHERE id = 28;
UPDATE public.auth_cookie SET cookie_value = 'c9a4b43f-fe13-43b5-a451-ea50dd209dde', user_id = 1 WHERE id = 29;
UPDATE public.auth_cookie SET cookie_value = 'c72142b0-05cb-4304-ac59-15c0df382d20', user_id = 1 WHERE id = 30;
UPDATE public.auth_cookie SET cookie_value = 'f69e4925-2a81-462a-8261-9ad63bd8eb62', user_id = 21 WHERE id = 31;
UPDATE public.auth_cookie SET cookie_value = '5310a950-0dca-4d8c-a6f6-cfc339b6fe33', user_id = 21 WHERE id = 32;
UPDATE public.auth_cookie SET cookie_value = '9daa2db2-7a56-488b-9a6f-c9ed894dce2b', user_id = 21 WHERE id = 33;
UPDATE public.auth_cookie SET cookie_value = 'eb48ec94-003d-4bf8-9b7f-8ca4c78bcac4', user_id = 21 WHERE id = 34;
UPDATE public.auth_cookie SET cookie_value = '1ecc7dd4-29af-4049-be59-d1e04abc56bf', user_id = 22 WHERE id = 35;
UPDATE public.auth_cookie SET cookie_value = '2a591a0d-bce2-4709-ae1b-aaf5503d85db', user_id = 21 WHERE id = 36;
UPDATE public.auth_cookie SET cookie_value = '5e3f99f0-c62a-42d5-b0a2-03f82d41b58d', user_id = 21 WHERE id = 37;
UPDATE public.auth_cookie SET cookie_value = '5f0679b2-6736-4462-b5d6-d3f0bcca6870', user_id = 1 WHERE id = 38;
UPDATE public.auth_cookie SET cookie_value = '2f0303ab-b2fa-4868-bab5-ea9fb644afbe', user_id = 1 WHERE id = 39;
UPDATE public.auth_cookie SET cookie_value = 'cefe221f-90e5-40a8-9eb9-5f83c4a40435', user_id = 23 WHERE id = 40;
UPDATE public.auth_cookie SET cookie_value = '82f04902-9ad2-4531-86fb-ab01867c42bb', user_id = 19 WHERE id = 41;
UPDATE public.auth_cookie SET cookie_value = 'ca08bcc1-ac0d-4787-9f57-1df3cfbb03c3', user_id = 18 WHERE id = 42;
UPDATE public.auth_cookie SET cookie_value = '94a61037-241d-4cb2-92fa-652325f36f74', user_id = 19 WHERE id = 43;
UPDATE public.auth_cookie SET cookie_value = 'c0c5823b-97be-43d4-a31d-946534da0871', user_id = 21 WHERE id = 44;
UPDATE public.auth_cookie SET cookie_value = 'f8f9d2cb-549d-4c3c-86d2-eed11bd3f8af', user_id = 23 WHERE id = 45;
UPDATE public.auth_cookie SET cookie_value = '162b7f45-60a7-4891-a7fc-ec4dd4f00dea', user_id = 21 WHERE id = 46;
UPDATE public.auth_cookie SET cookie_value = '20cd49b4-a3fc-4955-9ad3-9366d0466f6f', user_id = 21 WHERE id = 47;
UPDATE public.auth_cookie SET cookie_value = 'facf80ec-5060-4748-b682-ae4bcd9211dd', user_id = 21 WHERE id = 48;
UPDATE public.auth_cookie SET cookie_value = '9df15fae-2127-46cc-b0b6-8e5b763dae62', user_id = 21 WHERE id = 49;
UPDATE public.auth_cookie SET cookie_value = 'bbe393f1-47a7-4adf-909c-7ed97b84ff0d', user_id = 21 WHERE id = 50;
UPDATE public.auth_cookie SET cookie_value = '14c4d571-8434-4402-a4fc-c6c751468010', user_id = 21 WHERE id = 51;
UPDATE public.auth_cookie SET cookie_value = 'c804f0e2-18f9-4e86-bdb3-dedf27ee4cbf', user_id = 24 WHERE id = 52;
UPDATE public.auth_cookie SET cookie_value = '04fad022-1212-4df7-ae70-4a0d441392c1', user_id = 23 WHERE id = 53;
UPDATE public.basket SET user_id = 16 WHERE id = 1;
UPDATE public.basket SET user_id = 16 WHERE id = 12;
UPDATE public.basket SET user_id = 16 WHERE id = 13;
UPDATE public.basket SET user_id = 16 WHERE id = 14;
UPDATE public.basket SET user_id = 16 WHERE id = 15;
UPDATE public.basket SET user_id = 16 WHERE id = 16;
UPDATE public.basket SET user_id = 16 WHERE id = 17;
UPDATE public.basket SET user_id = 16 WHERE id = 18;
UPDATE public.basket SET user_id = 16 WHERE id = 19;
UPDATE public.basket SET user_id = 16 WHERE id = 20;
UPDATE public.basket SET user_id = 16 WHERE id = 21;
UPDATE public.basket SET user_id = 16 WHERE id = 22;
UPDATE public.basket SET user_id = 16 WHERE id = 23;
UPDATE public.basket SET user_id = 16 WHERE id = 24;
UPDATE public.basket SET user_id = 16 WHERE id = 25;
UPDATE public.basket SET user_id = 16 WHERE id = 26;
UPDATE public.basket SET user_id = 16 WHERE id = 27;
UPDATE public.basket SET user_id = 16 WHERE id = 28;
UPDATE public.basket SET user_id = 16 WHERE id = 29;
UPDATE public.basket SET user_id = 16 WHERE id = 30;
UPDATE public.basket SET user_id = 16 WHERE id = 31;
UPDATE public.basket SET user_id = 16 WHERE id = 32;
UPDATE public.basket SET user_id = 16 WHERE id = 33;
UPDATE public.basket SET user_id = 16 WHERE id = 34;
UPDATE public.basket SET user_id = 17 WHERE id = 35;
UPDATE public.basket SET user_id = 17 WHERE id = 36;
UPDATE public.basket SET user_id = 17 WHERE id = 37;
UPDATE public.basket SET user_id = 1 WHERE id = 38;
UPDATE public.basket SET user_id = 2 WHERE id = 39;
UPDATE public.basket SET user_id = 18 WHERE id = 40;
UPDATE public.basket SET user_id = 19 WHERE id = 41;
UPDATE public.basket SET user_id = 19 WHERE id = 42;
UPDATE public.basket SET user_id = 1 WHERE id = 43;
UPDATE public.basket SET user_id = 1 WHERE id = 44;
UPDATE public.basket SET user_id = 19 WHERE id = 45;
UPDATE public.basket SET user_id = 1 WHERE id = 46;
UPDATE public.basket SET user_id = 1 WHERE id = 47;
UPDATE public.basket SET user_id = 1 WHERE id = 48;
UPDATE public.basket SET user_id = 1 WHERE id = 49;
UPDATE public.basket SET user_id = 1 WHERE id = 50;
UPDATE public.basket SET user_id = 1 WHERE id = 51;
UPDATE public.basket SET user_id = 1 WHERE id = 52;
UPDATE public.basket SET user_id = 1 WHERE id = 53;
UPDATE public.basket SET user_id = 1 WHERE id = 54;
UPDATE public.basket SET user_id = 19 WHERE id = 55;
UPDATE public.basket SET user_id = 21 WHERE id = 56;
UPDATE public.basket SET user_id = 22 WHERE id = 57;
UPDATE public.basket SET user_id = 23 WHERE id = 58;
UPDATE public.basket_product SET basket_id = 38, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 1;
UPDATE public.basket_product SET basket_id = 40, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 1;
UPDATE public.basket_product SET basket_id = 56, product_id = 6;
UPDATE public.basket_product SET basket_id = 38, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 6;
UPDATE public.basket_product SET basket_id = 40, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 1;
UPDATE public.basket_product SET basket_id = 56, product_id = 5;
UPDATE public.basket_product SET basket_id = 25, product_id = 2;
UPDATE public.basket_product SET basket_id = 38, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 6;
UPDATE public.basket_product SET basket_id = 40, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 1;
UPDATE public.basket_product SET basket_id = 56, product_id = 6;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 40, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 56, product_id = 5;
UPDATE public.basket_product SET basket_id = 25, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 40, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 56, product_id = 6;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 1;
UPDATE public.basket_product SET basket_id = 40, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 56, product_id = 5;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 40, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 1;
UPDATE public.basket_product SET basket_id = 56, product_id = 5;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 39, product_id = 1;
UPDATE public.basket_product SET basket_id = 40, product_id = 5;
UPDATE public.basket_product SET basket_id = 41, product_id = 2;
UPDATE public.basket_product SET basket_id = 56, product_id = 5;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 39, product_id = 1;
UPDATE public.basket_product SET basket_id = 40, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 56, product_id = 5;
UPDATE public.basket_product SET basket_id = 25, product_id = 3;
UPDATE public.basket_product SET basket_id = 38, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 39, product_id = 2;
UPDATE public.basket_product SET basket_id = 40, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 57, product_id = 2;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 39, product_id = 3;
UPDATE public.basket_product SET basket_id = 40, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 1;
UPDATE public.basket_product SET basket_id = 57, product_id = 5;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 39, product_id = 1;
UPDATE public.basket_product SET basket_id = 40, product_id = 4;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 57, product_id = 6;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 39, product_id = 1;
UPDATE public.basket_product SET basket_id = 40, product_id = 6;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 56, product_id = 5;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 56, product_id = 5;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 56, product_id = 6;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 26, product_id = 2;
UPDATE public.basket_product SET basket_id = 38, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 26, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 5;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 26, product_id = 2;
UPDATE public.basket_product SET basket_id = 38, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 29, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 31, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 31, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 31, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 31, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 5;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 31, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 31, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 31, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 1;
UPDATE public.basket_product SET basket_id = 41, product_id = 5;
UPDATE public.basket_product SET basket_id = 31, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 2;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 41, product_id = 6;
UPDATE public.basket_product SET basket_id = 31, product_id = 3;
UPDATE public.basket_product SET basket_id = 34, product_id = 4;
UPDATE public.basket_product SET basket_id = 41, product_id = 3;
UPDATE public.basket_product SET basket_id = 31, product_id = 3;
UPDATE public.basket_product SET basket_id = 31, product_id = 2;
UPDATE public.basket_product SET basket_id = 34, product_id = 5;
UPDATE public.basket_product SET basket_id = 41, product_id = 4;
UPDATE public.basket_product SET basket_id = 31, product_id = 1;
UPDATE public.basket_product SET basket_id = 34, product_id = 3;
UPDATE public.basket_product SET basket_id = 38, product_id = 6;
UPDATE public.basket_product SET basket_id = 34, product_id = 6;
UPDATE public.basket_product SET basket_id = 38, product_id = 5;
UPDATE public.basket_product SET basket_id = 34, product_id = 1;
UPDATE public.basket_product SET basket_id = 38, product_id = 6;
UPDATE public.basket_product SET basket_id = 34, product_id = 6;
UPDATE public.basket_product SET basket_id = 38, product_id = 5;
UPDATE public.basket_product SET basket_id = 34, product_id = 6;
UPDATE public.basket_product SET basket_id = 38, product_id = 5;
UPDATE public.basket_product SET basket_id = 34, product_id = 6;
UPDATE public.basket_product SET basket_id = 47, product_id = 5;
UPDATE public.basket_product SET basket_id = 47, product_id = 5;
UPDATE public.basket_product SET basket_id = 48, product_id = 6;
UPDATE public.basket_product SET basket_id = 48, product_id = 6;
UPDATE public.basket_product SET basket_id = 48, product_id = 5;
UPDATE public.basket_product SET basket_id = 48, product_id = 5;
UPDATE public.basket_product SET basket_id = 54, product_id = 6;
UPDATE public.basket_product SET basket_id = 54, product_id = 5;
UPDATE public.basket_product SET basket_id = 54, product_id = 5;
UPDATE public.carrier_company SET the_number_of_trucks = 0, company_id = 1 WHERE id = 2;
UPDATE public.carrier_company SET the_number_of_trucks = 0, company_id = null WHERE id = 3;
UPDATE public.carrier_company SET the_number_of_trucks = 0, company_id = null WHERE id = 1;
UPDATE public.carrier_company SET the_number_of_trucks = 0, company_id = 17 WHERE id = 4;
UPDATE public.carrier_company SET the_number_of_trucks = 0, company_id = 18 WHERE id = 5;
UPDATE public.company SET company_name = 'OOO  "RafaelCar"', director_name = 'Marsel Rafaelievich', phone_number = '+79872921934', requisite_id = null, user_id = 1, carrier_id = 5, customer_id = null, company_role = 'Carrier' WHERE id = 18;
UPDATE public.company SET company_name = 'IPv4 OLya', director_name = 'OLya', phone_number = '+79276373687', requisite_id = null, user_id = 22, carrier_id = null, customer_id = 8, company_role = 'Customer' WHERE id = 20;
UPDATE public.company SET company_name = 'OOO "Express16"', director_name = 'Vasya Pupkin', phone_number = '+79872921924', requisite_id = null, user_id = 23, carrier_id = null, customer_id = 9, company_role = 'Customer' WHERE id = 21;
UPDATE public.company SET company_name = 'OOO "RaCar"', director_name = 'Azino Rafael', phone_number = '+79872921333', requisite_id = null, user_id = 21, carrier_id = null, customer_id = 7, company_role = 'Customer' WHERE id = 19;
UPDATE public.company SET company_name = 'OOO "JuLIK"', director_name = 'Azino Amigos', phone_number = '8(777)292-13-44', requisite_id = null, user_id = 16, carrier_id = null, customer_id = 5, company_role = 'Customer' WHERE id = 9;
UPDATE public.company SET company_name = 'OOO "TransTAT"', director_name = 'Хуан Карлос', phone_number = '8(789)116-13-36', requisite_id = null, user_id = 2, carrier_id = null, customer_id = 6, company_role = 'Customer' WHERE id = 16;
UPDATE public.company SET company_name = 'ИП Сидиков', director_name = 'Сидиков Марсель', phone_number = '8(777)292-19-93', requisite_id = null, user_id = 1, carrier_id = 1, customer_id = null, company_role = 'Carrier' WHERE id = 1;
UPDATE public.company SET company_name = 'OAO TATCARTAT', director_name = 'Vladislav Alekseev', phone_number = '+7(987)9136216', requisite_id = null, user_id = 18, carrier_id = 4, customer_id = null, company_role = 'Carrier' WHERE id = 17;
UPDATE public.customer_company SET company_id = 9 WHERE id = 5;
UPDATE public.customer_company SET company_id = 16 WHERE id = 6;
UPDATE public.customer_company SET company_id = 19 WHERE id = 7;
UPDATE public.customer_company SET company_id = 20 WHERE id = 8;
UPDATE public.customer_company SET company_id = 21 WHERE id = 9;
UPDATE public.logistic_service_user SET email = 'ivan99@gmail.ru', hash_password = '$2a$10$KVkJLwKO3Qb2r0H.WmS/.OTJcZSbS1/GWfncAzYp37pNflvuLoexq', first_name = 'Ivan', last_name = 'Ivanov', address = 'Fuchike 88, Kazan', phone_number = '+79872921967', login = 'avt_0105', company_id = null, profile_img = '../img/user.jpg' WHERE id = 24;
UPDATE public.logistic_service_user SET email = 'umilka@mail.ru', hash_password = '$2a$04$haa5TuuxGMha5EsBtXunbOlioV4W0GmhJ5Qbpqx6S9tQHcz2YDaD.', first_name = 'Emil', last_name = 'Sidor', address = 'Kazan, ...', phone_number = '+79882929979', login = 'lmaoswager', company_id = null, profile_img = '../img/user.jpg' WHERE id = 11;
UPDATE public.logistic_service_user SET email = 'customerexampleComp@yandex.ru', hash_password = '$2a$10$ONUfTIX.RsVXOkFA/s2KOOYf0IIap8B5Obt/Wu5ejZ7OZSTT4RJCq', first_name = 'Ivan', last_name = 'Ivanov', address = 'Chebocksary', phone_number = '+79772911333', login = 'ProCarrier', company_id = null, profile_img = '../img/user.jpg' WHERE id = 20;
UPDATE public.logistic_service_user SET email = 'customerexample99@yandex.ru', hash_password = '$2a$10$nu36YtzpUefcpo7yIkNcVufF3Re4x10FWjIcg3DmVHlXLQ2YdsdW6', first_name = 'Ivan', last_name = 'Sochkov', address = 'Chebocksary, st. Mirnaya d 18 kv 125', phone_number = '+79872921963', login = 'SomeUser16', company_id = 19, profile_img = '../img/user.jpg' WHERE id = 21;
UPDATE public.logistic_service_user SET email = 'rivaresam@gmail.com', hash_password = '$2a$10$o4mnkVmKaCcMOAH.3gGRH.YiWtyVbpUMVOLsL0NdPqGjakrRsJVDC', first_name = 'Olya', last_name = 'KIlina', address = 'Kazan', phone_number = '89274925454', login = 'Olya', company_id = 20, profile_img = '../img/user.jpg' WHERE id = 22;
UPDATE public.logistic_service_user SET email = 'ivan9@gmail.ru', hash_password = '$2a$10$4AH7j9cE.E5SxxZDePpe4uRQXYM.Q2QC9b6JaN7qiCq8oumT2GszW', first_name = 'Ivan', last_name = 'Ivanovich', address = 'Kazan, Fuchike 126 kv 46', phone_number = '+7(987)9136216', login = 'ivan16', company_id = 9, profile_img = '../img/user.jpg' WHERE id = 16;
UPDATE public.logistic_service_user SET email = 'aqua@ya.ru', hash_password = '$2a$10$TRh8Z8.WLlV0NGxDepwnK.H.bu4AGtfnbScrdOt.z2SC.OvfzVWgi', first_name = 'qwe', last_name = 'qwrqt', address = null, phone_number = null, login = 'aqua', company_id = null, profile_img = '../img/user.jpg' WHERE id = 17;
UPDATE public.logistic_service_user SET email = 'nadin-alekseeva@ya.ru', hash_password = '$2a$10$NSLsDLch8Ts7WpFBUudNEu/JAf64qYV8k97Y9r3vYm/HHnKnHH6QC', first_name = 'Nadin', last_name = 'Alekseeva', address = 'Kazan, Fuchike 126 kv 46', phone_number = '+7(987)9236216', login = 'nadin16', company_id = 17, profile_img = '../img/user.jpg' WHERE id = 18;
UPDATE public.logistic_service_user SET email = 'carlosboozer@mail.ru', hash_password = '$2a$10$JUoxHngy2K3MtTOIxxZSIuESXYLc0mMrdhq78W63yCw9ZQ7AD23L.', first_name = 'Carlos', last_name = 'Boozer', address = 'Moskow, Pr. Mira 126 kv 78', phone_number = '+7(987)9546216', login = 'Carlos16', company_id = null, profile_img = '../img/user.jpg' WHERE id = 19;
UPDATE public.logistic_service_user SET email = 'upalsharnanogu@mail.ru', hash_password = '$2a$04$haa5TuuxGMha5EsBtXunbOlioV4W0GmhJ5Qbpqx6S9tQHcz2YDaD.', first_name = 'Marsel', last_name = 'Sid', address = 'Kazan', phone_number = '+7997-002-30', login = 'sid116', company_id = null, profile_img = '../img/user.jpg' WHERE id = 4;
UPDATE public.logistic_service_user SET email = 'carlos@mail.ru', hash_password = '$2a$10$SnKPjvJOMFpW89fCtMVmKewx/1djorM5REKc/2N753p3A5NHYU8oO', first_name = 'Marat', last_name = 'Carlos', address = 'Kazakhstan', phone_number = '+798242124', login = 'Carlos116', company_id = 16, profile_img = '../img/user.jpg' WHERE id = 2;
UPDATE public.logistic_service_user SET email = 'ivan@gmail.ru', hash_password = '$2a$10$kQh5EENaKw4MhLxuFGEfgOMOTAY.hc4pvypzMZzWXxnCKxPPgCWYK', first_name = 'Ivan', last_name = 'Obыvan', address = 'Belarus', phone_number = '294-23-23', login = 'obivanKenOBI', company_id = null, profile_img = '../img/user.jpg' WHERE id = 3;
UPDATE public.logistic_service_user SET email = 'VlaAAlekseev@stud.kpfu.ru', hash_password = 'qwerty001', first_name = 'Vladislav', last_name = 'Alekseev', address = 'Kzn', phone_number = '+79872921965', login = 'VLADYAN', company_id = null, profile_img = '../img/user.jpg' WHERE id = 12;
UPDATE public.logistic_service_user SET email = 'VldAAlekseev@stud.kpfu.ru', hash_password = '$2a$10$g6u6lRorVCzpOIgI2AbEFOmBtmLaerHvjzF/eRELrn8xhWe72VciC', first_name = 'Vladislav', last_name = 'Alekseev', address = 'Kzn', phone_number = '+79872921963', login = 'Vlad007', company_id = null, profile_img = '../img/user.jpg' WHERE id = 15;
UPDATE public.logistic_service_user SET email = 'upaharnanogumarselu@mail.ru', hash_password = '$2a$04$haa5TuuxGMha5EsBtXunbOlioV4W0GmhJ5Qbpqx6S9tQHcz2YDaD.', first_name = 'Marsel', last_name = 'Sidor', address = 'Kazan, ...', phone_number = '+79882929979', login = 'lmaoswagger', company_id = null, profile_img = '../img/user.jpg' WHERE id = 10;
UPDATE public.logistic_service_user SET email = 'sidikov.marsel@gmail.com', hash_password = '$2a$10$kvD6sAkX3dj2vqTyu.4Vzuc2R5xRaojnq2JsTKFXSstZcLH79Fbg6', first_name = 'Marsel', last_name = 'Sidikov', address = 'Fuchike 128', phone_number = '+79882929979', login = 'marselka007', company_id = 18, profile_img = '../img/user.jpg' WHERE id = 1;
UPDATE public.logistic_service_user SET email = 'topcustomerexample@yandex.ru', hash_password = null, first_name = null, last_name = 'Sochkov', address = 'Fuchike 88, Kazan', phone_number = '+79872921924', login = 'CustomeR16', company_id = 21, profile_img = '../img/user.jpg' WHERE id = 23;
UPDATE public.product SET product_name = 'Термос', price = 1000, description = 'Thermos EveryNight-1000 - отличный термос, рассчитанный на интенсивную эксплуатацию. Большого объема (1 литр) хватит, чтобы обеспечить владельца любимым напитком на протяжении всего дня. Благодаря вакуумной изоляции и герметичности температура содержимого сохраняется в течение длительного периода: холод - 12 часов, тепло - 8. ', product_img = '../img/termos-thermos-everynight-1000.jpg' WHERE id = 2;
UPDATE public.product SET product_name = 'Apelas CS-4108PMQ-6', price = 3500, description = 'Набор торцевых головок CS-4108PMQ 1/2" & 1/4" 6-гранных 108пр. APELAS', product_img = '../img/apelascs-410.jpg' WHERE id = 1;
UPDATE public.product SET product_name = 'Защитные перчатки', price = 150, description = 'Для случая если что-то сломается', product_img = '../img/perchatki.png' WHERE id = 3;
UPDATE public.product SET product_name = 'Alan 42', price = 4300, description = 'Радиостанции Алан 42 400каналов', product_img = '../img/lan42-600x800.jpg' WHERE id = 6;
UPDATE public.product SET product_name = 'Маяк проблесковый на магните', price = 139, description = 'Маяк проблесковый на магните желтый 12V ( "стакан" h=140мм. в прикуриватель )', product_img = '../img/fonar-problesk-600x800.jpg' WHERE id = 5;
UPDATE public.product SET product_name = 'Лента 5-10 тонн стяжки крепления груза', price = 257, description = 'Лента (08м. 50мм) 5-10 тонн стяжки (ремня) крепления груза (25шт уп)', product_img = '../img/lenta-600x800.jpg' WHERE id = 4;
UPDATE public.tractor SET registration_number = '7MFK46RU116', years_of_exploitation = 3, mileage = 40000, carrier_company_id = null, driver_id = null, model = null, mark = null, type = null WHERE id = 2;
UPDATE public.trailer SET registration_number = '3BWE12RU116', years_of_exploitation = 4, mileage = 12000, tonnage = null, carrier_company_id = null, volume_in_cubic_meters = null, mark = null, type = null, inner_length = null, inner_width = null, inner_height = null WHERE id = 2;
